### PR TITLE
Fix camelCase property name

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by weaverryan** [comment]
Yes, great catch!

**Comment by bocharsky-bw** [comment]
@weaverryan You write an unique comment on each my PR and I think it's awesome! How did you do that? :)

**Comment by weaverryan** [comment]
@bocharsky-bw haha, it's only because I open each PR and like to comment manually :). The least I can do anyways when someone volunteers improvements either here or anywhere in the OS world.

**Comment by bocharsky-bw** [comment]
@weaverryan It's a very cool! I like your replies on each PR. You're picks very interesting phrases :)

**Pull request merged**
